### PR TITLE
Fixed the abusive usage of GST_STATE_NULL to pause all cached sounds …

### PR DESCRIPTION
**Pull request by yotabits**
…when a new sound play request is made.

According to this document:
https://gstreamer.freedesktop.org/documentation/plugin-development/basics/states.html
The GST_STATE_NULL should be used olny when no ressources is loaded/loaded.
The GST_STATE_PAUSED fits best to the requirement to have olny one sound
played at time.

Concerning the bug of the jumping sound volume, it has been fixed by replacing
the usage of GST_STATE_NULL by GST_STATE_PAUSED in specific cases.

Concerning the whole usage of the GST library this commit is just a "hot fix"
I think the GST library should not be used the way it is now, in my opinion
as we want to have olny one sound playing a time we need a unique sound
stream/channel and a unique gstsoud buffer containing multiple sounds.
In this buffer we should keep track off the sounds addresses. By this way to
play a given sound we just have to seek in the sound buffer.

### CODE REVIEW

**Comment by naveedhd** [comment]
I would like to know what actually happens with volume when we call the NULL. It would be good to include the script in this PR to reproduce the issue.

**Comment by yotabits** [comment]
Here is the code using the GST_STATE_NULL.
[test_sound.tar.gz](https://github.com/yujinrobot/audio_common/files/871233/test_sound.tar.gz)

**Comment by naveedhd** [comment]
@yotabits please add the script with a new commit.

Also would have been good if the changes from [here](https://github.com/ros-drivers/audio_common/pull/95/files) and additional be kept separated in 2 commits, but not an issue.

**Comment by naveedhd** [comment]
@hughie do you want this to be merged in `master`? If yes, then `ros:master` and `yujin:master` would divert..

Another solution would be to have a separate branch.

**Comment by hughie** [comment]
@naveedhd How about using separate branch for it? It seems better for later.

**Comment by naveedhd** [comment]
I have made a [new branch](https://github.com/yujinrobot/audio_common/tree/volume_fix_branch) with these changes which we can use for testing or stable release.

**Comment by naveedhd** [comment]
@yotabits some points I observed:

Tray icon instances of playback stream adds up with sounds. So you may see 3 - 4 bars depending on how many sounds are played during delivery. Good thing is they vanish after a while, but this confirms that this might not be the proper solution and we can't do much refactoring from the original code.

**Comment by naveedhd** [comment]
the jumping volume issue is fixed with changes. We will use the new branch until things run for few days/demo/stable-release, then we either fix it is ros-driver or yujin's repo. (don't merge this PR)

**Comment by yotabits** [comment]
@naveedhd 
> Tray icon instances of playback stream adds up with sounds. So you may see 3 - 4 bars depending on how many sounds are played during delivery.

This is because the actual code is using multiple sound streams in my opinion, and kill the sound stream as soon as the given stream is not used in a given time 

> I think the GST library should not be used the way it is now, in my opinion
as we want to have only one sound playing a time we need a unique sound
stream/channel and a unique gstsoud buffer containing multiple sounds.

@hughie 
I can refactor the code to use the sound library in a more appropriate way, let me know if this is an actual emergency or just let me know when there is need to do that.

**Pull request merged**
